// Mock API wrapper to simulate DeepSeek Formatting behavior

export const simulateAiFormatting = async (
  prompt: string,
  processAIResponse: (jsonString: string, blockTitle: string) => void
) => {
  return new Promise<void>((resolve) => {
    setTimeout(() => {
      let mockJsonStructure = "";
      let title = "Generated Draft";

      const lowerPrompt = prompt.toLowerCase();

      // Simple heuristics to mimic intent recognition
      if (lowerPrompt.includes("table") || lowerPrompt.includes("jadwali")) {
        title = "Data Table";
        mockJsonStructure = JSON.stringify({
          type: "doc",
          content: [
            { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "Structured Table" }] },
            {
              type: "table",
              content: [
                {
                  type: "tableRow",
                  content: [
                    { type: "tableHeader", content: [{ type: "paragraph", content: [{ type: "text", text: "Item" }] }] },
                    { type: "tableHeader", content: [{ type: "paragraph", content: [{ type: "text", text: "Amount" }] }] }
                  ]
                },
                {
                  type: "tableRow",
                  content: [
                    { type: "tableCell", content: [{ type: "paragraph", content: [{ type: "text", text: "Pens" }] }] },
                    { type: "tableCell", content: [{ type: "paragraph", content: [{ type: "text", text: "$5" }] }] }
                  ]
                },
                {
                  type: "tableRow",
                  content: [
                    { type: "tableCell", content: [{ type: "paragraph", content: [{ type: "text", text: "Paper (A4 Ream)" }] }] },
                    { type: "tableCell", content: [{ type: "paragraph", content: [{ type: "text", text: "$12" }] }] }
                  ]
                }
              ]
            }
          ]
        });
      } else {
        title = "Formatted Document";
        mockJsonStructure = JSON.stringify({
          type: "doc",
          content: [
            { type: "heading", attrs: { level: 1 }, content: [{ type: "text", text: "Document Title" }] },
            { type: "paragraph", content: [{ type: "text", text: "This is the perfectly formatted text generated by the AI, exactly as requested." }] },
            { type: "paragraph", content: [
                { type: "text", text: "Here is some " },
                { type: "text", marks: [{ type: "bold" }], text: "bolded text" },
                { type: "text", text: ", and some " },
                { type: "text", marks: [{ type: "italic" }], text: "italic text" },
                { type: "text", text: "." }
              ]
            }
          ]
        });
      }

      processAIResponse(mockJsonStructure, title);
      resolve();
    }, 1500); // Simulate network latency
  });
};
